services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: employeedb
      POSTGRES_USER: spring-person-db
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
