spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcDataAutoConfiguration
  security:
    user:
      name: admin
      password: admin123

jwt:
  secret: dGVzdCBzZWNyZXQgZm9yIHRlc3RpbmcgcHVycG9zZXMgb25seQ==
  expiration: 86400000