global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'employee-management-api'
    static_configs:
      - targets: ['employee-management-api:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s